services:
  unbound:
    image: alpinelinux/unbound:latest
    container_name: unbound
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    restart: unless-stopped
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf
    networks: [monitor-net]
networks:
  monitor-net:
    external: true  # the network already exists (created with `docker network create monitor-net`)